export const applications = [
  {
    name: "Frances R. Kostka",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "qualified",
    id: 1,
  },
  {
    name: "Aaliyah Sanderson",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Finance",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Shortlisted",
    category: "task",
    id: 2,
  },
  {
    name: "Michael D. McKee",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Computer Science",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "qualified",
    id: 3,
  },
  {
    name: "Christel R. Sclafani",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Shortlisted",
    category: "disqualified",
    id: 4,
  },
  {
    name: "Jerry S. Pollock",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "qualified",
    id: 5,
  },
  {
    name: "Frances R. Kostka",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "qualified",
    id: 6,
  },
  {
    name: "Aaliyah Sanderson",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Finance",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "task",
    id: 7,
  },
  {
    name: "Michael D. McKee",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Computer Science",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "qualified",
    id: 25,
  },
  {
    name: "Christel R. Sclafani",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "disqualified",
    id: 8,
  },
  {
    name: "Jerry S. Pollock",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "qualified",
    id: 9,
  },
  {
    name: "Frances R. Kostka",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Shortlisted",
    category: "qualified",
    id: 10,
  },
  {
    name: "Aaliyah Sanderson",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Finance",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "task",
    id: 11,
  },
  {
    name: "Michael D. McKee",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Computer Science",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Offer",
    category: "qualified",
    id: 12,
  },
  {
    name: "Christel R. Sclafani",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Technical Interview",
    category: "disqualified",
    id: 13,
  },
  {
    name: "Jerry S. Pollock",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Technical Interview",
    category: "qualified",
    id: 14,
  },
  {
    name: "Frances R. Kostka",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "qualified",
    id: 15,
  },
  {
    name: "Aaliyah Sanderson",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Finance",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Applied",
    category: "task",
    id: 16,
  },
  {
    name: "Michael D. McKee",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Computer Science",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Offer",
    category: "qualified",
    id: 17,
  },
  {
    name: "Christel R. Sclafani",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Technical Interview",
    category: "disqualified",
    id: 18,
  },
  {
    name: "Jerry S. Pollock",
    nationality: "Saudi Arabia",
    degree: "Bachelor in Marketing",
    year: "(2023 - 2023)",
    hashTags: ["#top_candidate", "#top_candidate"],
    tags: ["New York", "Marketing", "London"],
    score: 7,
    type: "Offer",
    category: "qualified",
    id: 19,
  },
];
